name: flutter_workflow
description: A powerful and customizable node-based UI library for Flutter.
version: 0.1.0
publish_to: 'none' # Prevents accidental publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  vector_math: ^2.1.4
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  rxdart: ^0.28.0

flutter:
  assets:
    - lib/src/features/canvas/presentation/shaders/background.frag
